parameters:

services:
    # HELPER
    hbm.helper.blitline:
        class: HBM\HelperBundle\Services\Blitline
        arguments: ["%hbm.helper.blitline%", "@hbm.helper.s3", "@hbm.helper.hmac", "@router"]
        calls:
            - [ setContainer, [ "@service_container" ] ]

    hbm.helper.cleverreach:
        class: HBM\HelperBundle\Services\CleverReach
        arguments: ["%hbm.helper.cleverreach%"]

    hbm.helper.hmac:
        class: HBM\HelperBundle\Services\Hmac
        calls:
            - [ setContainer, [ "@service_container" ] ]

    hbm.helper.s3:
        class: HBM\HelperBundle\Services\S3
        arguments: ["%hbm.helper.s3%"]
        calls:
            - [ setContainer, [ "@service_container" ] ]

    hbm.helper.stringsanitizer:
        arguments: ["%hbm.helper.stringsanitizer%"]
        class: HBM\HelperBundle\Services\StringSanitizer

    # TWIG
    hbm.twig_extension.string_sanitizer:
        class: HBM\HelperBundle\Twig\StringSanitizerExtension
        arguments: ["@hbm.helper.stringsanitizer"]
        tags:
            - { name: twig.extension }
