services:
    _defaults:
        public: true

    ############################################################################
    # HELPER - SCREENSHOT                                                      #
    ############################################################################

    HBM\HelperBundle\Service\Screenshot\BlitlineHelper:
        arguments: ["%hbm.helper.blitline%", "@hbm.helper.s3", "@hbm.helper.hmac", "@router"]

    hbm.helper.blitline:
        alias: HBM\HelperBundle\Service\Screenshot\BlitlineHelper

    ############################################################################

    HBM\HelperBundle\Service\Screenshot\ScreenshotApiHelper:
        arguments: ["%hbm.helper.screenshotapi%"]

    hbm.helper.screenshotapi:
        alias: HBM\HelperBundle\Service\Screenshot\ScreenshotApiHelper

    ############################################################################

    HBM\HelperBundle\Service\Screenshot\ScreenshotLayerHelper:
        arguments: ["%hbm.helper.screenshotlayer%"]

    hbm.helper.screenshotlayer:
        alias: HBM\HelperBundle\Service\Screenshot\ScreenshotLayerHelper

    ############################################################################

    HBM\HelperBundle\Service\Screenshot\WebshrinkerHelper:
        arguments: ["%hbm.helper.webshrinker%"]

    hbm.helper.webshrinker:
        alias: HBM\HelperBundle\Service\Screenshot\WebshrinkerHelper

    ############################################################################
    # HELPER                                                                   #
    ############################################################################

    HBM\HelperBundle\Service\BitlyHelper:
        arguments: ["%hbm.helper.bitly%"]

    hbm.helper.bitly:
        alias: HBM\HelperBundle\Service\BitlyHelper

    ############################################################################

    HBM\HelperBundle\Service\HmacHelper:
        arguments: ["%hbm.helper.hmac%"]

    hbm.helper.hmac:
        alias: HBM\HelperBundle\Service\HmacHelper

    ############################################################################

    HBM\HelperBundle\Service\S3Helper:
        arguments: ["%hbm.helper.s3%"]

    hbm.helper.s3:
        alias: HBM\HelperBundle\Service\S3Helper

    ############################################################################

    HBM\HelperBundle\Service\SanitizingHelper:
        arguments: ["%hbm.helper.sanitizing%"]

    hbm.helper.sanitizing:
        alias: HBM\HelperBundle\Service\SanitizingHelper

    ############################################################################
