parameters:

services:
    _defaults: { public: true }

    # HELPER
    hbm.helper.bitly:
        class: HBM\HelperBundle\Services\BitlyHelper
        arguments: ["%hbm.helper.bitly%"]

    hbm.helper.screenshotapi:
        class: HBM\HelperBundle\Services\ScreenshotApiHelper
        arguments: ["%hbm.helper.screenshotapi%"]

    hbm.helper.webshrinker:
        class: HBM\HelperBundle\Services\WebshrinkerHelper
        arguments: ["%hbm.helper.webshrinker%"]

    hbm.helper.blitline:
        class: HBM\HelperBundle\Services\BlitlineHelper
        arguments: ["%hbm.helper.blitline%", "@hbm.helper.s3", "@hbm.helper.hmac", "@router"]
        calls:
            - [ setContainer, [ "@service_container" ] ]

    hbm.helper.cleverreach:
        class: HBM\HelperBundle\Services\CleverReachHelper
        arguments: ["%hbm.helper.cleverreach%"]

    hbm.helper.hmac:
        class: HBM\HelperBundle\Services\HmacHelper
        arguments: ["%hbm.helper.hmac%"]

    hbm.helper.s3:
        class: HBM\HelperBundle\Services\S3Helper
        arguments: ["%hbm.helper.s3%"]
        calls:
            - [ setContainer, [ "@service_container" ] ]

    hbm.helper.sanitizing:
        arguments: ["%hbm.helper.sanitizing%"]
        class: HBM\HelperBundle\Services\SanitizingHelper

    # TWIG
    hbm.twig_extension.sanitizing:
        class: HBM\HelperBundle\Twig\SanitizingExtension
        arguments: ["@hbm.helper.sanitizing"]
        tags:
            - { name: twig.extension }
